In [1]:
!pip install pandas
import pandas as pd

[notice] A new release of pip is available: 23.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: pandas in c:\users\anshu\onedrive\desktop\project\feedback\fee\lib\site-packages (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\anshu\onedrive\desktop\project\feedback\fee\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\users\anshu\onedrive\desktop\project\feedback\fee\lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: pytz>=2020.1 in c:\users\anshu\onedrive\desktop\project\feedback\fee\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: numpy>=1.22.4 in c:\users\anshu\onedrive\desktop\project\feedback\fee\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: six>=1.5 in c:\users\anshu\onedrive\desktop\project\feedback\fee\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
chunks = pd.read_csv("complaints.csv", chunksize=10000)

filtered = []

for chunk in chunks:
    filtered.append(chunk[chunk["Product"] == "Credit card"])

df = pd.concat(filtered)

In [3]:
print(df.sample())

        Date received      Product  \
8507361    2025-07-04  Credit card

                                        Sub-product  \
8507361  General-purpose credit card or charge card

                                      Issue      Sub-issue  \
8507361  Other features, terms, or problems  Other problem

                              Consumer complaint narrative  \
8507361  On XX/XX/year>, I filed a motion requesting an...

        Company public response                            Company State  \
8507361                     NaN  CAPITAL ONE FINANCIAL CORPORATION    AZ

        ZIP code Tags Submitted via Date sent to company  \
8507361    85029  NaN           Web           2025-07-04

        Company response to consumer Timely response?  Complaint ID
8507361      Closed with explanation              Yes    14446580.0

In [4]:
df = df[
    [
        "Consumer complaint narrative",
        "Product",
        "Issue",
        "Company",
        "Date received",
        "State"
    ]
]

In [5]:
df.describe()

,Consumer complaint narrative,Product,Issue,Company,Date received,State
count,124472,334330,334323,334330,334330,332542
unique,115308,1,49,1076,29931,63
top,See the attached documents. I want the bureau ...,Credit card,Problem with a purchase shown on your statement,"CITIBANK, N.A.",2025-01-16,CA
freq,835,334330,58354,40764,527,45128

In [6]:
new_df= df.dropna(subset=["Consumer complaint narrative"])

In [7]:
new_df.describe()

,Consumer complaint narrative,Product,Issue,Company,Date received,State
count,124472,124472,124472,124472,124472,123998
unique,115308,1,45,724,7837,61
top,See the attached documents. I want the bureau ...,Credit card,Problem with a purchase shown on your statement,"CITIBANK, N.A.",2025-12-02,CA
freq,835,124472,27550,15402,221,17270

In [8]:
# new_df.memory_usage(deep=True).sum() / (1024**2)

In [9]:
duplicates = new_df.duplicated(
    subset=["Consumer complaint narrative"]
).sum()
print(duplicates)

9164

In [10]:
complaint_counts=(
 new_df.groupby("Consumer complaint narrative").size().reset_index(name="frequency")
)

In [11]:
new_df["words_count"]=(
    new_df["Consumer complaint narrative"].str.split().str.len()
)
new_df["words_count"].describe()

C:\Users\anshu\AppData\Local\Temp\ipykernel_7044\3894858424.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["words_count"]=(

count    124472.000000
mean        210.291817
std         219.436815
min           2.000000
25%          75.000000
50%         158.000000
75%         272.000000
max        6469.000000
Name: words_count, dtype: float64

In [12]:
pd.set_option("display.max_colwidth", None)
print(new_df["Consumer complaint narrative"].sample(20,random_state=42))

8285308                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       XXXX  I've been a card holder for over XXXX  years and my daughter has been a card holder for over XXXX  years. \n\nWe recently experienced our accounts being merged. My daughter purchase are being applied to my account causing my balance to go extremely high. It's impacting my XXXX  payment, and when I call wich has been multiple times they canceled my account without my consent internally to prevent further billing. But this action is a direct impact to my credit. All I wanted is to have my account corrected to reflect the ture purchase. The Supervisor wasn't much help, she never addressed any of the notes from her colleagues addressing the known issue her name was XXXX XXXX  XXXX. The bottom line, they are billing me for my purchases and for my daughter purchase. \nI appreciate your attention to this unlawful matter. \n\nThanks
11362076                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      I was notified a credit account was opened through capital one in my name. I was not the one to open this.
11530410                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          I am writing to formally file a complaint regarding an account listed in your system that utilizes my residential address. \nOn or around XX/XX/XXXX, I received a letter from American Express dated XX/XX/XXXX. The letter was addressed to XXXX XXXX and referenced an account ending in XXXX. The correspondence confirmed the cancellation of said account. \nXXXX XXXX XXXX does not reside at this address ( XXXX XXXX XXXX, XXXX XXXX, NJ ). \nThis individual has no legal right to use this property for billing or correspondence. The association of this individual with my residence suggests either a clerical error in your database or potential application fraud where my address was used without my consent. \nI request that you immediately take the following actions : 1. Remove my address ( XXXX XXXX XXXX, XXXX XXXX, NJ XXXX ) from the profile associated with XXXX XXXX and Account # XXXX immediately. \n2. Cease all future correspondence addressed to this individual at my home.\n\n3. Investigate this account for potential fraudulent activity regarding the falsification of residence. \nPlease consider this letter a formal notice to correct your records.
6170197                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      I purchase air ticket from XXXX from XXXX to XXXX. I was getting cheaper ticket from else where so i cancelled this ticket within XXXX hours window that allows me to get full refund. XXXX processed full refund but Apple Credit card is keep putting me charges on my card. I sent them XXXX receipt and refund confirmation but they keep charging me saying charge is from XXXX. I never brought ticket directly from XXXX. so why would apple not reaching out to XXXX and complete investigation of this dispute and keep coming back to me with charges for ticket that i never flew or use. thanks
4062846                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   I have my Bank of America credit card set up to make auto payments for the minimum amount and it has been set up that way since I first got the credit card. The payment is set up for the XXXX and is usually taken from my account by the XXXX. When my payment came out this month my auto payment was changed to take the full statement balance and I did not authorize that. I never went in and changed it from the minimum to statement balance. The minimum payment to be take was to be XXXX on XX/XX/XXXX but instead a full statement balance amount of XXXX was taken on XX/XX/XXXX which was not authorized and I now have a negative bank account balance. I want to know who changed my auto pay settings as I did not as their system is old and outdated and it is complicated to go in and change these settings. I called the company and they are supposed to reverse the payment but stated that it may take up to 10 days for the reversal which doesn't help as my bank account is currently negative.

In [13]:
new_df["clean_text"] = (
    new_df["Consumer complaint narrative"]
    .str.lower()
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

C:\Users\anshu\AppData\Local\Temp\ipykernel_7044\2611869757.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["clean_text"] = (

In [14]:
idx = 10

print("Original:\n")
print(new_df.iloc[idx]["Consumer complaint narrative"])

print("\nCleaned:\n")
print(new_df.iloc[idx]["clean_text"])

Original:

On XX/XX/year> I went online to XXXX XXXX to purchase XXXX round trip tickets to XXXX XXXX. The total cost for the TWO tickets was {$2800.00}. I went through the XXXX payment link and used my Citi MasterCard to purchase the tickets. The purchase was declined by Citi Card because they wanted to verify that it was me making the purchase. I verified it was me and Citi alerted me that the purchase could be made. I tried again and it was declined. I contacted Citi again and they said it was all set to book.

The next day, on XX/XX/year> I went back online to XXXX XXXX to book the flights. The purchase was approved.

In XXXX, I received my Citi Card XXXX statement, and it showed TWO PURCHASES for XXXX XXXX for the exact same flights. I was charged TWICE for the ticket purchase. I contacted Citi Card IMMEDIATELY and they agreed that there was a duplicate charge on my credit card for the ticket purchase - one for {$2800.00} on XX/XX/XXXX ( the one they initially declined ) and one for {$2800.00} on XX/XX/XXXX that they approved. They reversed the charge and said they would contact XXXX directly to get the credit.

Over one month later, I received a letter from Citi stating that XXXX refused to credit me for the duplicate charge, as I had made the purchase with the Citi Card and put the duplicate charge back on my credit card.

I immediately contacted Citi Card and told a representative at Citi Card that I did not deny making a purchase with my Citi Card but I WAS CHARGED TWICE. The representative stated that Citi had put the claim through incorrectly. She said it was put through denying that I made the purchase. Once I told her I was not denying I made the purchase with my Citi Card, but that it was charged twice, she said she would resubmit the claim correctly and that I would be credited for the duplicate charge within ten days. THIS WAS IN XXXX.

In XXXX, I received another letter from Citi Card that the information I have submitted was reviewed and that they attempted to resolve this dispute with the merchant ( XXXX ) and they are unwilling to issue a credit and that they are closing the investigation.

I contacted XXXX and they sent me an email ADMITTING I WAS CHARGED TWICE for the same two tickets and that it was up to the BANK ( Citi ) to credit my account.

This has been going on for MONTHS AND MONTHS. What should be an easy, immediate adjustment to my credit card for a XXXX  duplicate charge on my credit card has caused me hours and hours on the phone, writing emails and an enormous amount of stress - never mind the impact on my credit score due to an additional {$2800.00} being reported as credit usage that I did not use.

Bottom lineXXXX  Citi Card is outright refusing to credit me. Telling me XXXX will not credit the duplicate charge and that I am basically " out of luck. '' This is NOT how credit card companies are supposed protect the customers from obvious duplicate charges by a merchant. It is THEIR responsibility to get this rectified. NOT ME.

It is now XX/XX/XXXX, and I am still carrying an additional balance of {$2800.00} on my Citi Card that I did not incur. I want it credited along with all the interest that has accrued since XX/XX/year>.

THANK YOU.

Cleaned:

on xx/xx/year> i went online to xxxx xxxx to purchase xxxx round trip tickets to xxxx xxxx. the total cost for the two tickets was {$2800.00}. i went through the xxxx payment link and used my citi mastercard to purchase the tickets. the purchase was declined by citi card because they wanted to verify that it was me making the purchase. i verified it was me and citi alerted me that the purchase could be made. i tried again and it was declined. i contacted citi again and they said it was all set to book. the next day, on xx/xx/year> i went back online to xxxx xxxx to book the flights. the purchase was approved. in xxxx, i received my citi card xxxx statement, and it showed two purchases for xxxx xxxx for the exact same flights. i was charged twice for the ticket purchase. i contacted citi card immediately and they agreed that there was a duplicate charge on my credit card for the ticket purchase - one for {$2800.00} on xx/xx/xxxx ( the one they initially declined ) and one for {$2800.00} on xx/xx/xxxx that they approved. they reversed the charge and said they would contact xxxx directly to get the credit. over one month later, i received a letter from citi stating that xxxx refused to credit me for the duplicate charge, as i had made the purchase with the citi card and put the duplicate charge back on my credit card. i immediately contacted citi card and told a representative at citi card that i did not deny making a purchase with my citi card but i was charged twice. the representative stated that citi had put the claim through incorrectly. she said it was put through denying that i made the purchase. once i told her i was not denying i made the purchase with my citi card, but that it was charged twice, she said she would resubmit the claim correctly and that i would be credited for the duplicate charge within ten days. this was in xxxx. in xxxx, i received another letter from citi card that the information i have submitted was reviewed and that they attempted to resolve this dispute with the merchant ( xxxx ) and they are unwilling to issue a credit and that they are closing the investigation. i contacted xxxx and they sent me an email admitting i was charged twice for the same two tickets and that it was up to the bank ( citi ) to credit my account. this has been going on for months and months. what should be an easy, immediate adjustment to my credit card for a xxxx duplicate charge on my credit card has caused me hours and hours on the phone, writing emails and an enormous amount of stress - never mind the impact on my credit score due to an additional {$2800.00} being reported as credit usage that i did not use. bottom linexxxx citi card is outright refusing to credit me. telling me xxxx will not credit the duplicate charge and that i am basically " out of luck. '' this is not how credit card companies are supposed protect the customers from obvious duplicate charges by a merchant. it is their responsibility to get this rectified. not me. it is now xx/xx/xxxx, and i am still carrying an additional balance of {$2800.00} on my citi card that i did not incur. i want it credited along with all the interest that has accrued since xx/xx/year>. thank you.

In [15]:
new_df = new_df.reset_index(drop=True)

In [16]:
new_df.sample(5)

,Consumer complaint narrative,Product,Issue,Company,Date received,State,words_count,clean_text
101100,"On XX/XX/year>, my Robinhood Gold Card account was closed by the issuer for alleged business-type transactions. I received an email titled Notice about your Robinhood Gold Card account on the same date.\n\nI do not operate a business and all transactions on the account were for personal use. After receiving the notice, I contacted Robinhood through their in-app chat support to request clarification. \n\nSpecifically, I requested : Identification of the transactions that were classified as business-type The criteria used to determine that classification Confirmation of whether the decision was automated or manually reviewed Reconsideration of the account closure Robinhood declined to provide transaction-level details or the standards used in their determination. I was informed that reinstatement requests are not accepted under any circumstances. Additionally, all remaining rewards points were forfeited as a result of the closure. \n\nAt this time, I have not been provided any specific evidence or explanation showing how my transactions violated the Cardholder Agreement. \n\nI am requesting : Identification of the specific transactions deemed business-related The criteria used to classify those transactions Confirmation of whether this determination was automated or manually reviewed A fair reconsideration of the account closure I am seeking transparency and a documented basis for this decision.",Credit card,Closing your account,ROBINHOOD MARKETS INC.,2026-02-25,NY,203,"on xx/xx/year>, my robinhood gold card account was closed by the issuer for alleged business-type transactions. i received an email titled notice about your robinhood gold card account on the same date. i do not operate a business and all transactions on the account were for personal use. after receiving the notice, i contacted robinhood through their in-app chat support to request clarification. specifically, i requested : identification of the transactions that were classified as business-type the criteria used to determine that classification confirmation of whether the decision was automated or manually reviewed reconsideration of the account closure robinhood declined to provide transaction-level details or the standards used in their determination. i was informed that reinstatement requests are not accepted under any circumstances. additionally, all remaining rewards points were forfeited as a result of the closure. at this time, i have not been provided any specific evidence or explanation showing how my transactions violated the cardholder agreement. i am requesting : identification of the specific transactions deemed business-related the criteria used to classify those transactions confirmation of whether this determination was automated or manually reviewed a fair reconsideration of the account closure i am seeking transparency and a documented basis for this decision."
93855,"This letter concerns the transaction below made with my Citi XXXX XXXX XXXX : XXXX * XXXXXXXX XXXX XXXX XXXX XXXX XXXXXXXX CA {$110.00} on XX/XX/XXXX I opened a case with the card issuer, Citibank, XXXX XX/XX/XXXX and the Case number is XXXX. The reason for Dispute was that Goods/ services are not as expected. \n\nOn XX/XX/XXXX I purchased a ticket to an event called XXXXXXXX XXXX XXXXXXXX XXXXXXXX XXXX XXXX XXXX XXXX XXXX. The event was to take place on XX/XX/XXXX. \n\nHowever, the merchant has significantly changed the details of the event. The finalized event was not what I expected. The merchant has changed the following : - The artist XXXX is no longer performing at this event. This is the main reason why I purchased this ticket - The event has moved outdoors. I can not be outdoors that long due to health concerns. \n\nBecause of these changes, I requested a refund from the merchant, but with no response. Because of the event not having the expected outcome, I have filed a dispute. \n\nCitibank resolved the case in the Merchant 's favor on XX/XX/XXXX. I have sent a follow up on XX/XX/XXXX and told them that the dispute was not resolved correctly. I called Citibank and asked the reason why, and their response was that they need support evidence and asked me to send the evidence to XXXX Attached to this letter is the support documentation that I emailed XXXX on XX/XX/XXXX 1. The actual ticket entitled XXXXXXXX XXXX XXXX XXXX XXXX XXXX XXXX XXXX XXXX. \n\n2. Email order confirmation detailing the event. \n- The Event Title is : XXXX XXXX XXXX XXXX XXXX XXXX XXXX XXXX XXXX - Event Location : XXXXXXXX XXXX XXXX XXXX XXXX XXXX XXXX XXXX XXXX CA - Event Date : Sat XX/XX/XXXX, XXXX 3. An email I sent to the merchant requesting a refund. \n\n4. An article published by a third party detailing the changes that the XXXX made which was not the final event that I expected. \n\nPlease note the actual evidence the Merchant provided to Citi 's Dispute department detailed a completely different event, which is evidence that the Merchant changed the event. \n\n1. An event with the following details, completely different from what I purchased : - Event Title : XXXX XXXX XXXX XXXX XXXX XXXX XXXX XXXX XXXX XXXXXXXX - Event Location : XXXX XXXX XXXX, XXXX XXXX, CA - Event Date : Saturday XXXX, XXXX, XXXX No one has responded to my email ever since I provided the evidence that the Dispute department requested on XX/XX/XXXX. I did not expect the case to be closed and not investigated further without proper communication. \n\nI then called Citibank asking why nothing has been done since I emailed them the supporting documentation, and their response was that they can not see the pictures attached to the email. This was after the chargeback window was closed. They requested that I physically print out the supporting documentation and mail them the papers, and that they will request to re-open the dispute. I did as requested on XX/XX/XXXX. I got a response back in the mail from that XXXX has denied the request to re-open the dispute. \n\nI called Citibank customer service again to be told that they will request to re-open the dispute again. I responded that it will make no difference as it was denied before.",Credit card,Problem with a purchase shown on your statement,"CITIBANK, N.A.",2025-12-09,CA,565,"this letter concerns the transaction below made with my citi xxxx xxxx xxxx : xxxx * xxxxxxxx xxxx xxxx xxxx xxxx xxxxxxxx ca {$110.00} on xx/xx/xxxx i opened a case with the card issuer, citibank, xxxx xx/xx/xxxx and the case number is xxxx. the reason for dispute was that goods/ services are not as expected. on xx/xx/xxxx i purchased a ticket to an event called xxxxxxxx xxxx xxxxxxxx xxxxxxxx xxxx xxxx xxxx xxxx xxxx. the event was to take place on xx/xx/xxxx. however, the merchant has significantly changed the details of the event. the finalized event was not what i expected. the merchant has changed the following : - the artist xxxx is no longer performing at this event. this is the main reason why i purchased this ticket - the event has moved outdoors. i can not be outdoors that long due to health concerns. because of these changes, i requested a refund from the merchant, but with no response. because of the event not having the expected outcome, i have filed a dispute. citibank resolved the case in the merchant 's favor on xx/xx/xxxx. i have sent a follow up on xx/xx/xxxx and told them that the dispute was not resolved correctly. i called citibank and asked the reason why, and their response was that they need support evidence and asked me to send the evidence to xxxx attached to this letter is the support documentation that i emailed xxxx on xx/xx/xxxx 1. the actual ticket entitled xxxxxxxx xxxx xxxx xxxx xxxx xxxx xxxx xxxx xxxx. 2. email order confirmation detailing the event. - the event title is : xxxx xxxx xxxx xxxx xxxx xxxx xxxx xxxx xxxx - event location : xxxxxxxx xxxx xxxx xxxx xxxx xxxx xxxx xxxx xxxx ca - event date : sat xx/xx/xxxx, xxxx 3. an email i sent to the merchant requesting a refund. 4. an article published by a third party detailing the changes that the xxxx made which was not the final event that i expected. please note the actual evidence the merchant provided to citi 's dispute department detailed a completely different event, which is evidence that the merchant changed the event. 1. an event with the following details, completely different from what i purchased : - event title : xxxx xxxx xxxx xxxx xxxx xxxx xxxx xxxx xxxx xxxxxxxx - event location : xxxx xxxx xxxx, xxxx xxxx, ca - event date : saturday xxxx, xxxx, xxxx no one has responded to my email ever since i provided the evidence that the dispute department requested on xx/xx/xxxx. i did not expect the case to be closed and not investigated further without proper communication. i then called citibank asking why nothing has been done since i emailed them the supporting documentation, and their response was that they can not see the pictures attached to the email. this was after the chargeback window was closed. they requested that i physically print out the supporting documentation and mail them the papers, and that they will request to re-open the dispute. i did as requested on xx/xx/xxxx. i got a response back in the mail from that xxxx has denied the request to re-open the dispute. i called citibank customer service again to be told that they will request to re-open the dispute again. i responded that it will make no difference as it was denied before."
41831,I noticed Two purchases in XXXX that I didnt make in XXXX XX/XX/XXXX XXXX estimate {$130.00} each time estimate total {$260.00}. \n\nThen two other purchases at Two stores.,Credit card,Problem with a purchase shown on your statement,"BANK OF AMERICA, NATIONAL ASSOCIATION",2024-08-13,CA,28,i noticed two purchases in xxxx that i didnt make in xxxx xx/xx/xxxx xxxx estimate {$130.00} each time estimate total {$260.00}. then two other purchases at two stores.
40567,"I received a letter in the mail dated XX/XX/year>, from Capital One asking to mail a copy of my driver 's license to verify the information included on an application. I was unsure if this was scam/junk mail. I subsequently received a letter in the mail from XXXX XXXX XXXX, regarding a data breach that XXXX have involved my personal information. This prompted me to look at my credit reports and sure enough, there was a hard inquiry from Capital One. there was also a phone number that is not mine nor never was associated with me on my report under contacts and inquiry analysis. I reported a fraud alert, froze my XXXX report, and tried to dispute the inquiry online. However, I learned you can not dispute inquiries online, but can do so by mail or telephone. I spoke with XXXX, who informed me that they can not remove the hard inquiry with the fraud alert and that I need to contact the creditor ( Captial One ) to remove the hard inquiry. XXXX informed me that the fraud alert will be passed on to the other 2 bureaus, but the freeze will not. I placed a freeze on the other 2 bureaus. I then spoke with Capital One, the fraudulent application will cancel in 3-5 days and the hard inquiries will take 60 to 90 days to remove from my credit report after the investigation is done by their fraud team. I was then advised to contact the 3 bureaus again and report a victim statement for the fraudulent application. I then spoke to XXXX again and was questioned whether it would benefit me to do that. That question thoroughly confused me. This has never happened to me before ; I'm just trying to take all the right steps that I need to. I was advised to report a victim statement. XXXX then asked if I'd like to remove it from my report, in which I answered yes, of course. I then was told that it can not be removed without an FTC report or police report.",Credit card,Improper use of your report,CAPITAL ONE FINANCIAL CORPORATION,2024-07-30,NY,349,"i received a letter in the mail dated xx/xx/year>, from capital one asking to mail a copy of my driver 's license to verify the information included on an application. i was unsure if this was scam/junk mail. i subsequently received a letter in the mail from xxxx xxxx xxxx, regarding a data breach that xxxx have involved my personal information. this prompted me to look at my credit reports and sure enough, there was a hard inquiry from capital one. there was also a phone number that is not mine nor never was associated with me on my report under contacts and inquiry analysis. i reported a fraud alert, froze my xxxx report, and tried to dispute the inquiry online. however, i learned you can not dispute inquiries online, but can do so by mail or telephone. i spoke with xxxx, who informed me that they can not remove the hard inquiry with the fraud alert and that i need to contact the creditor ( captial one ) to remove the hard inquiry. xxxx informed me that the fraud alert will be passed on to the other 2 bureaus, but the freeze will not. i placed a freeze on the other 2 bureaus. i then spoke with capital one, the fraudulent application will cancel in 3-5 days and the hard inquiries will take 60 to 90 days to remove from my credit report after the investigation is done by their fraud team. i was then advised to contact the 3 bureaus again and report a victim statement for the fraudulent application. i then spoke to xxxx again and was questioned whether it would benefit me to do that. that question thoroughly confused me. this has never happened to me before ; i'm just trying to take all the right steps that i need to. i was advised to report a victim statement. xxxx then asked if i'd like to remove it from my report, in which i answered yes, of course. i then was told that it can not be removed without an ftc report or police report."

In [17]:
!pip install sentence-transformers

Requirement already satisfied: sentence-transformers in c:\users\anshu\onedrive\desktop\project\feedback\fee\lib\site-packages (5.6.0)
Requirement already satisfied: huggingface-hub>=0.23.0 in c:\users\anshu\onedrive\desktop\project\feedback\fee\lib\site-packages (from sentence-transformers) (1.24.0)
Requirement already satisfied: torch>=1.11.0 in c:\users\anshu\onedrive\desktop\project\feedback\fee\lib\site-packages (from sentence-transformers) (2.13.0)
Requirement already satisfied: scikit-learn>=0.22.0 in c:\users\anshu\onedrive\desktop\project\feedback\fee\lib\site-packages (from sentence-transformers) (1.7.2)
Requirement already satisfied: scipy>=1.0.0 in c:\users\anshu\onedrive\desktop\project\feedback\fee\lib\site-packages (from sentence-transformers) (1.15.3)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in c:\users\anshu\onedrive\desktop\project\feedback\fee\lib\site-packages (from sentence-transformers) (5.14.1)
Requirement already satisfied: typing_extensions>=4.5.0 in c:\users\anshu\onedrive\desktop\project\feedback\fee\lib\site-packages (from sentence-transformers) (4.16.0)
Requirement already satisfied: numpy>=1.20.0 in c:\users\anshu\onedrive\desktop\project\feedback\fee\lib\site-packages (from sentence-transformers) (2.2.6)
Requirement already satisfied: tqdm>=4.0.0 in c:\users\anshu\onedrive\desktop\project\feedback\fee\lib\site-packages (from sentence-transformers) (4.69.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\anshu\onedrive\desktop\project\feedback\fee\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in c:\users\anshu\onedrive\desktop\project\feedback\fee\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.5.2)
Requirement already satisfied: packaging>=20.9 in c:\users\anshu\onedrive\desktop\project\feedback\fee\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (26.2)
Requirement already satisfied: pyyaml>=5.1 in c:\users\anshu\onedrive\desktop\project\feedback\fee\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (6.0.3)
Requirement already satisfied: click<9.0.0,>=8.4.2 in c:\users\anshu\onedrive\desktop\project\feedback\fee\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (8.4.2)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\anshu\onedrive\desktop\project\feedback\fee\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2026.6.0)
Requirement already satisfied: filelock>=3.10.0 in c:\users\anshu\onedrive\desktop\project\feedback\fee\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.32.0)
Requirement already satisfied: joblib>=1.2.0 in c:\users\anshu\onedrive\desktop\project\feedback\fee\lib\site-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\anshu\onedrive\desktop\project\feedback\fee\lib\site-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.6.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\anshu\onedrive\desktop\project\feedback\fee\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.4.2)
Requirement already satisfied: jinja2 in c:\users\anshu\onedrive\desktop\project\feedback\fee\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: setuptools>=77.0.3 in c:\users\anshu\onedrive\desktop\project\feedback\fee\lib\site-packages (from torch>=1.11.0->sentence-transformers) (83.0.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\anshu\onedrive\desktop\project\feedback\fee\lib\site-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: colorama in c:\users\anshu\onedrive\desktop\project\feedback\fee\lib\site-packages (from tqdm>=4.0.0->sentence-transformers) (0.4.6)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\anshu\onedrive\desktop\project\feedback\fee\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: safetensors>=0.8.0 in c:\users\anshu\onedrive\desktop\project\feedback\fee\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.8.0)
Requirement already satisfied: regex>=2025.10.22 in c:\users\anshu\onedrive\desktop\project\feedback\fee\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2026.7.19)
Requirement already satisfied: typer in c:\users\anshu\onedrive\desktop\project\feedback\fee\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.27.0)
Requirement already satisfied: anyio in c:\users\anshu\onedrive\desktop\project\feedback\fee\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.14.2)
Requirement already satisfied: httpcore==1.* in c:\users\anshu\onedrive\desktop\project\feedback\fee\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)
Requirement already satisfied: certifi in c:\users\anshu\onedrive\desktop\project\feedback\fee\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2026.7.22)
Requirement already satisfied: idna in c:\users\anshu\onedrive\desktop\project\feedback\fee\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.18)
Requirement already satisfied: h11>=0.16 in c:\users\anshu\onedrive\desktop\project\feedback\fee\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\anshu\onedrive\desktop\project\feedback\fee\lib\site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\anshu\onedrive\desktop\project\feedback\fee\lib\site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\anshu\onedrive\desktop\project\feedback\fee\lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in c:\users\anshu\onedrive\desktop\project\feedback\fee\lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\anshu\onedrive\desktop\project\feedback\fee\lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.0.4)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\anshu\onedrive\desktop\project\feedback\fee\lib\site-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (2.20.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\anshu\onedrive\desktop\project\feedback\fee\lib\site-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (4.2.0)
Requirement already satisfied: exceptiongroup>=1.0.2 in c:\users\anshu\onedrive\desktop\project\feedback\fee\lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.3.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\anshu\onedrive\desktop\project\feedback\fee\lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.1.2)

[notice] A new release of pip is available: 23.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [18]:
dev_df = new_df.sample(5000, random_state=42).reset_index(drop=True)

In [ ]:
# from sentence_transformers import SentenceTransformer
# model = SentenceTransformer("all-MiniLM-L6-v2")
# embeddings=model.encode(
#     dev_df["clean_text"].tolist(),
#     batch_size=32,
#     show_progress_bar=True,
#     convert_to_numpy=True
# )

In [27]:
import numpy as np

embeddings = np.load("embeddings.npy")

In [ ]:
# np.save("embeddings.npy",embeddings)

In [22]:
pip install hdbscan umap-learn

Requirement already satisfied: hdbscan in c:\users\anshu\onedrive\desktop\project\feedback\fee\lib\site-packages (0.8.44)
Requirement already satisfied: umap-learn in c:\users\anshu\onedrive\desktop\project\feedback\fee\lib\site-packages (0.5.12)
Requirement already satisfied: joblib>=1.0 in c:\users\anshu\onedrive\desktop\project\feedback\fee\lib\site-packages (from hdbscan) (1.5.3)
Requirement already satisfied: scipy>=1.0 in c:\users\anshu\onedrive\desktop\project\feedback\fee\lib\site-packages (from hdbscan) (1.15.3)
Requirement already satisfied: scikit-learn>=1.6 in c:\users\anshu\onedrive\desktop\project\feedback\fee\lib\site-packages (from hdbscan) (1.7.2)
Requirement already satisfied: numpy<3,>=1.20 in c:\users\anshu\onedrive\desktop\project\feedback\fee\lib\site-packages (from hdbscan) (2.2.6)
Requirement already satisfied: pynndescent>=0.5 in c:\users\anshu\onedrive\desktop\project\feedback\fee\lib\site-packages (from umap-learn) (0.6.0)
Requirement already satisfied: numba>=0.51.2 in c:\users\anshu\onedrive\desktop\project\feedback\fee\lib\site-packages (from umap-learn) (0.66.0)
Requirement already satisfied: tqdm in c:\users\anshu\onedrive\desktop\project\feedback\fee\lib\site-packages (from umap-learn) (4.69.0)
Requirement already satisfied: llvmlite<0.49,>=0.48.0dev0 in c:\users\anshu\onedrive\desktop\project\feedback\fee\lib\site-packages (from numba>=0.51.2->umap-learn) (0.48.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\anshu\onedrive\desktop\project\feedback\fee\lib\site-packages (from scikit-learn>=1.6->hdbscan) (3.6.0)
Requirement already satisfied: colorama in c:\users\anshu\onedrive\desktop\project\feedback\fee\lib\site-packages (from tqdm->umap-learn) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

768-D embeddings
        ↓
UMAP (50 dimensions)
        ↓
HDBSCAN

In [23]:
#why to use umap
#faster clustring,less memory,often better cluster

In [28]:
import umap
reducer = umap.UMAP(
    n_neighbors=15,
    n_components=50,
    metric="cosine",
    random_state=42
)
reduced_embeddings=reducer.fit_transform(embeddings)

c:\Users\anshu\OneDrive\Desktop\project\feedback\fee\lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

In [29]:
print(reduced_embeddings.shape)

(5000, 50)

In [30]:
import hdbscan
clusterer = hdbscan.HDBSCAN(
    min_cluster_size=20,
    metric="euclidean",
    prediction_data=True
)
labels = clusterer.fit_predict(reduced_embeddings)

In [31]:
import numpy as np

print("Clusters:", len(np.unique(labels)) - (1 if -1 in labels else 0))
print("Noise:", np.sum(labels == -1))

Clusters: 32
Noise: 1851

In [32]:
dev_df["cluster"] = labels

In [33]:
cluster_5 = dev_df[dev_df["cluster"] == 5]

cluster_5["clean_text"].head(10)

78                                                                 i ensure that i always pay on time, and i'm certain of this fact. what i don't understand is why this company is reporting late payments for certain months. per usc 1666b, billing errors need to be corrected, or they owe me {$1000.00} for each inaccurately reported account.
138     timely payments are always a priority for me, and i am certain about this. however, i am unsure why this company is reporting me as late in certain months, which should not be the case. according to usc 1666b, any billing error should be corrected, or they will be liable to pay me {$1000.00} for each account reporting inaccurately.
182                                                                i ensure that i always pay on time, and i'm certain of this fact. what i don't understand is why this company is reporting late payments for certain months. per usc 1666b, billing errors need to be corrected, or they owe me {$1000.00} for each inaccurately reported account.
658                                                                                                                                                                                                                                                                                                  i always pay on time and never missed a payment.
747                                                                                                                 i know for sure that i pay my bills when theyre due. what i dont understand is why ive been marked late by this company for certain months. usc 1666b says billing mistakes must be fixed and my account updated as paid on time.
1222                                                                        ensuring punctuality in my payments is a priority. however, what perplexes me is the occasional reporting of late payments by this company, contrary to my records. as per usc 1666b, rectifying billing errors promptly and reflecting payments accurately is mandatory.
1294    timely payments are always a priority for me, and i am certain about this. however, i am unsure why this company is reporting me as late in certain months, which should not be the case. according to usc 1666b, any billing error should be corrected, or they will be liable to pay me {$1000.00} for each account reporting inaccurately.
1297          i consistently make on-time payments, of which i am certain. what i'm uncertain about is why this company is reporting me as late in certain months, which should not be the case. according to usc 1666b, any billing errors should be corrected, or they will be liable to pay me {$1000.00} for each account reporting inaccurately.
1357                                                                                                  i always pay on time. i am sure of this. what i am not sure is why this company is reporting me late on certain months which should not occur. based on usc 1666b any billing error should be corrected and should be updated to paid as agreed
1423                                                    consistency in paying on time is my motto. i'm firm about it. yet, i'm bewildered by the occasional tardiness in the company 's reporting, which shouldn't be the case. usc 1666b mandates that any billing errors must be rectified promptly and reflected correctly in the payment records.
Name: clean_text, dtype: object

In [34]:
import numpy as np

clusters = np.unique(labels)

print("Total Clusters:", len(clusters) - (1 if -1 in clusters else 0))
print("Noise:", np.sum(labels == -1))

Total Clusters: 32
Noise: 1851

In [35]:
cluster_sizes = (
    dev_df["cluster"]
    .value_counts()
    .sort_values(ascending=False)
)

print(cluster_sizes)

cluster
-1     1851
 13     693
 16     289
 24     242
 31     173
 21     163
 3      146
 20     129
 25     114
 17     105
 14     102
 8      102
 11      98
 23      87
 12      71
 0       57
 15      54
 27      49
 18      43
 7       41
 9       40
 28      38
 5       36
 2       33
 6       32
 19      30
 22      30
 10      29
 29      27
 26      26
 4       24
 1       23
 30      23
Name: count, dtype: int64

In [36]:
largest_cluster = cluster_sizes.index[0]

print("Largest cluster:", largest_cluster)

samples = dev_df[dev_df["cluster"] == largest_cluster]["clean_text"].head(10)

for i, complaint in enumerate(samples, 1):
    print(f"\nComplaint {i}")
    print(complaint)
    print("-" * 80)

Largest cluster: -1

Complaint 1
xxxx i've been a card holder for over xxxx years and my daughter has been a card holder for over xxxx years. we recently experienced our accounts being merged. my daughter purchase are being applied to my account causing my balance to go extremely high. it's impacting my xxxx payment, and when i call wich has been multiple times they canceled my account without my consent internally to prevent further billing. but this action is a direct impact to my credit. all i wanted is to have my account corrected to reflect the ture purchase. the supervisor wasn't much help, she never addressed any of the notes from her colleagues addressing the known issue her name was xxxx xxxx xxxx. the bottom line, they are billing me for my purchases and for my daughter purchase. i appreciate your attention to this unlawful matter. thanks
--------------------------------------------------------------------------------

Complaint 2
i have had a store credit card with target since xxxx. almost xxxx weeks ago, i attempted to use my credit card in the app to make a purchase on xx/xx/xxxx ( sometime between my screenshot at xxxx xxxx and xxxx xxxx is when i finally submitted with a different credit card for my order ) and it said it was denied and to contact my credit company. to be clear, i pay the card off every month and it was not behind nor was i over my limit. i went online and it said my account was fine. i checked the app for my purchase, my physical credit card and the website and all showed the correct credit card. nothing was indicated as an issue online. my card doesn't expire until xxxx so that couldn't be the issue either. i called target credit the next day and they " congratulated '' me that my account was closed and they chose to open a regular mastercard credit card for me without my consent. i do not need another regular credit card, i have xxxx great cards already and i only have the target store card to save 5 % on my target purchases. i told the gentleman that i did not want a credit card and that i was never asked if that was okay, i was never informed that this was happening and even their own credit website never gave me the information. i even checked my statement, there was nothing. he told me i should have received a letter and also a new credit card. i received neither. it is not okay to open up an entirely new credit card in my name without my consent or even asking if it was okay. i told my husband and he showed me an article online that i was entitled to opt out of this. i told the gentleman on the phone that i didn't want nor ask for this card and yet i was never told i could keep my old card. they made the decision to close my account and not allow me to use the card that i, by rights should still be able to use. i work at a xxxx xxxx and if for some reason we have to send them a new card ( of the same type ), unless it's due to imminent fraud, the old card will still work for some time, so we don't put our members in a bind. i was told by the gentleman that they had sent me the card just a few weeks prior and didn't give me a chance to even start using the thing ( had i wanted it ). if you need to find the call, i called their credit # ( xxxx ) at xxxx xxxx and the call lasted xxxx minutes. my target store card is my xxxx oldest credit account. this will have a detrimental impact on my credit. also, although it's a small amount of money, i had to pay the 5 % more on my target purchases because i no longer had a card i could use. i use the card to buy groceries, what if i didn't have an alternative way to buy groceries? i'm blessed that i do, but what if i relied on that card for food? i would have no way to buy groceries. regardless, this is a big issue. i now will have a new credit account on my credit report, which will bring down my credit score. i will no longer have an active card from xxxx and this will also have a detrimental impact on my credit. finally, i was given zero options to decline this xxxx that i do not want nor did i ask for. i will only ever use my target account at target. i use my rewards credit cards from elsewhere for all other purchases.
--------------------------------------------------------------------------------

Complaint 3
the complaint below focuses on capital one 's failure to investigate a charge tied to a merchant 's illegal and dangerous activity, which is a violation of their duties under the fair credit billing act complaint regarding failure to investigate disputed charge tied to merchant misconduct account holder : xxxx xxxx xxxx credit card account : ends in xxxx xxxx. what happened : i am filing this complaint because capital one has failed to comply with its duties under the fair credit billing act ( fcba ) by refusing to investigate a serious billing error tied to a merchants unlawful and reckless conduct, and by allowing the merchant to continue harassing charge attempts on my maxed-out card. the disputed charge is around {$4800.00} balance related to an xxxx rental vehicle ( agreement # xxxx ). the debt is subject to a legal dispute because the merchant ( xxxx xxxx xxxx, via its contracted agent, xxxx xxxx ) committed a breach of the peace during a repossession attempt, which voids the legality of the entire debt under the uniform commercial code ( ucc ). - date of merchant misconduct : xx/xx/year>. the xxxx agent struck my occupied vehicle with a tow lift, initiated an unauthorized tow while i was inside, and then pursued me through traffic in a dangerous and reckless manner in a public lot in xxxx, alabama. this is a tort of reckless endangerment and a clear violation of xxxx repossession rules. - legal documentation : i have formally reported this incident to the xxxx police department ( case # xxxx ) and have provided this number to capital one. i have also placed xxxx on formal notice of a civil claim for xxxx of xxxx and xxxx. - xxxx admissions : my correspondence proves xxxx acknowledged the agent works under their loss prevention unit, making them vicariously liable for the illegal actions. xxxx. capital ones failure to act : despite this debt being directly tied to a reported crime and a major civil liability claim against the merchant, capital one has failed to intervene or properly investigate the validity of the charge. - failure to investigate ( fcba ) : capital one has a duty to investigate charges related to defective service or non-receipt of goods as agreed. a service rendered illegally ( an unlawful repossession ) qualifies as a defective or void service. capital one is failing to meet the required investigation period ( xxxx days ) for this severe, documented dispute. - enabling harassment : capital one continues to enable xxxx automated billing system to repeatedly attempt to charge the full {$4800.00} debt, capturing minimum payments and keeping my card maxed out, despite my formal notice of legal dispute and the ongoing police report. this enables the merchant 's harassing behavior. xxxx. requested resolution : i have exhausted my efforts trying to resolve this with frontline agents. i demand the following corrective actions : - immediately place a permanent block on all future charge attempts from xxxx xxxx xxxx ( xxxx ) and any related entities to my account ending in xxxx. - acknowledge and initiate a formal investigation into the validity of the {$4800.00} charge under the fcba, recognizing that the merchants illegal conduct ( breach of peace ) voids the service. - immediately cease reporting the {$4800.00} disputed amount as delinquent to credit bureaus until the investigation is complete. i will attach all xxxx correspondence and the police incident number as evidence. this matter requires immediate escalation to capital ones legal/compliance team.
--------------------------------------------------------------------------------

Complaint 4
i am reporting this account as identity theft i did not open or authorized this account to be opened this account was open fraudulently using my information
--------------------------------------------------------------------------------

Complaint 5
in xx/xx/year> a request was made it increase a credit card ending xxxx, i did not get an explanation of why the credit limit increase was denied. in xx/xx/year>, a request was made to increase credit limit on credit card ending in xxxx. once again nothing was sent in written communication stating why i was denied for the credit limit increase.
--------------------------------------------------------------------------------

Complaint 6
since around xxxx, i 've held a bank of america credit card. on xxxx xxxx, xxxx. i presented it in a branch in the xxxx area. i explained that i wanted to payoff and close the account. they gave me the payoff number ( {$1200.00} ). i wrote them a check, which cleared the next day, for that amount. they said i had to actually close the account over the phone, i verified with the staff that if i completed these steps, the process would be complete, and i would n't have to do, or pay, anything else. i called their call center the next day and closed the account. i verified with the csr who closed the account for me that i would n't have to do, or pay, anything else. on xxxx/xxxx/xxxx, i got an email with a new statement. i checked it to ensure i did n't have to do anything else, and that the balance was {$0.00}. it was n't. boa had charged me {$23.00} further interest. this is unacceptable. i paid off the account, closed it, verified twice that the process was complete, and they still charged me interest against a closed account. if they 'd have told me when i wrote them the payoff check that it 'd have been another {$23.00}, i 'd have paid it. they did n't. as we agreed, i consider this account closed, and i do not owe them an additional {$23.00}. please help me have this debt removed from my account, and from my general record.
--------------------------------------------------------------------------------

Complaint 7
on xx/xx/year> i ask them help me with a credit card charge i never use because i cant get into my account because someone hack my account and they making me pay {$9000.00} on a credit.
--------------------------------------------------------------------------------

Complaint 8
dear cfpb, i have a secured credit card with citibank which is changed to unsecured card and i have been calling n waitting for the check release the secured amount {$2500.00} for rhat credit card. they told me to wait then today they told me someone cashed my check but their system doesnt have info as of who, where and when did it happen!! i requested a case number but they wont send me any confirmation whatsoever to report to the police. they told me i have to wait for some form that might be sent to me via mail within 14 days to fill out. i called customer service second time today and their manager told me same thing, no info no help at all! please help me, it's a big bank but the service is so terrible and lil customer like me can do nothing! thank so much and look forward for your reply!
--------------------------------------------------------------------------------

Complaint 9
i was charged over {$100.00} in returned payment fees on my citi xxxx credit card due to payments being processed during very brief periods when my account balance temporarily dipped below the payment amount. in each case, the funds were available the same day, and this was a timing issue rather than a pattern of insufficient funds. i have contacted citibank multiple times and was told to obtain a letter from my bank explaining the returned payments. my bank has stated they can not provide such a letter for momentary balance fluctuations. i am requesting a goodwill review and refund of these fees based on my account history and the nature of these transactions. i have taken steps to ensure this does not happen again. i would like citibank to be fair in reviewing my situation and consider the timing related to these charges being so close to each other and the funds being available after re-running the payments.
--------------------------------------------------------------------------------

Complaint 10
loss job due to medical disability- had credit protection insurance with credit card company which i understood such claim would be covered - my claim for benefit was not processed nor were any fees returned as i paid for a credit product they did not assist with - ssdi claim took several months for determination and receipt of ssdi benefits to pay back credit card company. due to the number of fees applied and increase accrued credit card company charged off balance and written off as profit/loss- please update xxxx and xxxx credit bureaus to reflect xxxx balance. provide me a 1099-c for debt cancellation. and refund me for fees paid/interest assessed for credit product.
--------------------------------------------------------------------------------

In [37]:
largest_cluster = cluster_sizes[cluster_sizes.index != -1].index[0]

In [38]:
largest_cluster = cluster_sizes.index[0]

print("Largest cluster:", largest_cluster)

samples = dev_df[dev_df["cluster"] == largest_cluster]["clean_text"].head(10)

for i, complaint in enumerate(samples, 1):
    print(f"\nComplaint {i}")
    print(complaint)
    print("-" * 80)

Largest cluster: -1

Complaint 1
xxxx i've been a card holder for over xxxx years and my daughter has been a card holder for over xxxx years. we recently experienced our accounts being merged. my daughter purchase are being applied to my account causing my balance to go extremely high. it's impacting my xxxx payment, and when i call wich has been multiple times they canceled my account without my consent internally to prevent further billing. but this action is a direct impact to my credit. all i wanted is to have my account corrected to reflect the ture purchase. the supervisor wasn't much help, she never addressed any of the notes from her colleagues addressing the known issue her name was xxxx xxxx xxxx. the bottom line, they are billing me for my purchases and for my daughter purchase. i appreciate your attention to this unlawful matter. thanks
--------------------------------------------------------------------------------

Complaint 2
i have had a store credit card with target since xxxx. almost xxxx weeks ago, i attempted to use my credit card in the app to make a purchase on xx/xx/xxxx ( sometime between my screenshot at xxxx xxxx and xxxx xxxx is when i finally submitted with a different credit card for my order ) and it said it was denied and to contact my credit company. to be clear, i pay the card off every month and it was not behind nor was i over my limit. i went online and it said my account was fine. i checked the app for my purchase, my physical credit card and the website and all showed the correct credit card. nothing was indicated as an issue online. my card doesn't expire until xxxx so that couldn't be the issue either. i called target credit the next day and they " congratulated '' me that my account was closed and they chose to open a regular mastercard credit card for me without my consent. i do not need another regular credit card, i have xxxx great cards already and i only have the target store card to save 5 % on my target purchases. i told the gentleman that i did not want a credit card and that i was never asked if that was okay, i was never informed that this was happening and even their own credit website never gave me the information. i even checked my statement, there was nothing. he told me i should have received a letter and also a new credit card. i received neither. it is not okay to open up an entirely new credit card in my name without my consent or even asking if it was okay. i told my husband and he showed me an article online that i was entitled to opt out of this. i told the gentleman on the phone that i didn't want nor ask for this card and yet i was never told i could keep my old card. they made the decision to close my account and not allow me to use the card that i, by rights should still be able to use. i work at a xxxx xxxx and if for some reason we have to send them a new card ( of the same type ), unless it's due to imminent fraud, the old card will still work for some time, so we don't put our members in a bind. i was told by the gentleman that they had sent me the card just a few weeks prior and didn't give me a chance to even start using the thing ( had i wanted it ). if you need to find the call, i called their credit # ( xxxx ) at xxxx xxxx and the call lasted xxxx minutes. my target store card is my xxxx oldest credit account. this will have a detrimental impact on my credit. also, although it's a small amount of money, i had to pay the 5 % more on my target purchases because i no longer had a card i could use. i use the card to buy groceries, what if i didn't have an alternative way to buy groceries? i'm blessed that i do, but what if i relied on that card for food? i would have no way to buy groceries. regardless, this is a big issue. i now will have a new credit account on my credit report, which will bring down my credit score. i will no longer have an active card from xxxx and this will also have a detrimental impact on my credit. finally, i was given zero options to decline this xxxx that i do not want nor did i ask for. i will only ever use my target account at target. i use my rewards credit cards from elsewhere for all other purchases.
--------------------------------------------------------------------------------

Complaint 3
the complaint below focuses on capital one 's failure to investigate a charge tied to a merchant 's illegal and dangerous activity, which is a violation of their duties under the fair credit billing act complaint regarding failure to investigate disputed charge tied to merchant misconduct account holder : xxxx xxxx xxxx credit card account : ends in xxxx xxxx. what happened : i am filing this complaint because capital one has failed to comply with its duties under the fair credit billing act ( fcba ) by refusing to investigate a serious billing error tied to a merchants unlawful and reckless conduct, and by allowing the merchant to continue harassing charge attempts on my maxed-out card. the disputed charge is around {$4800.00} balance related to an xxxx rental vehicle ( agreement # xxxx ). the debt is subject to a legal dispute because the merchant ( xxxx xxxx xxxx, via its contracted agent, xxxx xxxx ) committed a breach of the peace during a repossession attempt, which voids the legality of the entire debt under the uniform commercial code ( ucc ). - date of merchant misconduct : xx/xx/year>. the xxxx agent struck my occupied vehicle with a tow lift, initiated an unauthorized tow while i was inside, and then pursued me through traffic in a dangerous and reckless manner in a public lot in xxxx, alabama. this is a tort of reckless endangerment and a clear violation of xxxx repossession rules. - legal documentation : i have formally reported this incident to the xxxx police department ( case # xxxx ) and have provided this number to capital one. i have also placed xxxx on formal notice of a civil claim for xxxx of xxxx and xxxx. - xxxx admissions : my correspondence proves xxxx acknowledged the agent works under their loss prevention unit, making them vicariously liable for the illegal actions. xxxx. capital ones failure to act : despite this debt being directly tied to a reported crime and a major civil liability claim against the merchant, capital one has failed to intervene or properly investigate the validity of the charge. - failure to investigate ( fcba ) : capital one has a duty to investigate charges related to defective service or non-receipt of goods as agreed. a service rendered illegally ( an unlawful repossession ) qualifies as a defective or void service. capital one is failing to meet the required investigation period ( xxxx days ) for this severe, documented dispute. - enabling harassment : capital one continues to enable xxxx automated billing system to repeatedly attempt to charge the full {$4800.00} debt, capturing minimum payments and keeping my card maxed out, despite my formal notice of legal dispute and the ongoing police report. this enables the merchant 's harassing behavior. xxxx. requested resolution : i have exhausted my efforts trying to resolve this with frontline agents. i demand the following corrective actions : - immediately place a permanent block on all future charge attempts from xxxx xxxx xxxx ( xxxx ) and any related entities to my account ending in xxxx. - acknowledge and initiate a formal investigation into the validity of the {$4800.00} charge under the fcba, recognizing that the merchants illegal conduct ( breach of peace ) voids the service. - immediately cease reporting the {$4800.00} disputed amount as delinquent to credit bureaus until the investigation is complete. i will attach all xxxx correspondence and the police incident number as evidence. this matter requires immediate escalation to capital ones legal/compliance team.
--------------------------------------------------------------------------------

Complaint 4
i am reporting this account as identity theft i did not open or authorized this account to be opened this account was open fraudulently using my information
--------------------------------------------------------------------------------

Complaint 5
in xx/xx/year> a request was made it increase a credit card ending xxxx, i did not get an explanation of why the credit limit increase was denied. in xx/xx/year>, a request was made to increase credit limit on credit card ending in xxxx. once again nothing was sent in written communication stating why i was denied for the credit limit increase.
--------------------------------------------------------------------------------

Complaint 6
since around xxxx, i 've held a bank of america credit card. on xxxx xxxx, xxxx. i presented it in a branch in the xxxx area. i explained that i wanted to payoff and close the account. they gave me the payoff number ( {$1200.00} ). i wrote them a check, which cleared the next day, for that amount. they said i had to actually close the account over the phone, i verified with the staff that if i completed these steps, the process would be complete, and i would n't have to do, or pay, anything else. i called their call center the next day and closed the account. i verified with the csr who closed the account for me that i would n't have to do, or pay, anything else. on xxxx/xxxx/xxxx, i got an email with a new statement. i checked it to ensure i did n't have to do anything else, and that the balance was {$0.00}. it was n't. boa had charged me {$23.00} further interest. this is unacceptable. i paid off the account, closed it, verified twice that the process was complete, and they still charged me interest against a closed account. if they 'd have told me when i wrote them the payoff check that it 'd have been another {$23.00}, i 'd have paid it. they did n't. as we agreed, i consider this account closed, and i do not owe them an additional {$23.00}. please help me have this debt removed from my account, and from my general record.
--------------------------------------------------------------------------------

Complaint 7
on xx/xx/year> i ask them help me with a credit card charge i never use because i cant get into my account because someone hack my account and they making me pay {$9000.00} on a credit.
--------------------------------------------------------------------------------

Complaint 8
dear cfpb, i have a secured credit card with citibank which is changed to unsecured card and i have been calling n waitting for the check release the secured amount {$2500.00} for rhat credit card. they told me to wait then today they told me someone cashed my check but their system doesnt have info as of who, where and when did it happen!! i requested a case number but they wont send me any confirmation whatsoever to report to the police. they told me i have to wait for some form that might be sent to me via mail within 14 days to fill out. i called customer service second time today and their manager told me same thing, no info no help at all! please help me, it's a big bank but the service is so terrible and lil customer like me can do nothing! thank so much and look forward for your reply!
--------------------------------------------------------------------------------

Complaint 9
i was charged over {$100.00} in returned payment fees on my citi xxxx credit card due to payments being processed during very brief periods when my account balance temporarily dipped below the payment amount. in each case, the funds were available the same day, and this was a timing issue rather than a pattern of insufficient funds. i have contacted citibank multiple times and was told to obtain a letter from my bank explaining the returned payments. my bank has stated they can not provide such a letter for momentary balance fluctuations. i am requesting a goodwill review and refund of these fees based on my account history and the nature of these transactions. i have taken steps to ensure this does not happen again. i would like citibank to be fair in reviewing my situation and consider the timing related to these charges being so close to each other and the funds being available after re-running the payments.
--------------------------------------------------------------------------------

Complaint 10
loss job due to medical disability- had credit protection insurance with credit card company which i understood such claim would be covered - my claim for benefit was not processed nor were any fees returned as i paid for a credit product they did not assist with - ssdi claim took several months for determination and receipt of ssdi benefits to pay back credit card company. due to the number of fees applied and increase accrued credit card company charged off balance and written off as profit/loss- please update xxxx and xxxx credit bureaus to reflect xxxx balance. provide me a 1099-c for debt cancellation. and refund me for fees paid/interest assessed for credit product.
--------------------------------------------------------------------------------

In [39]:
cluster_sizes = (
    dev_df["cluster"]
    .value_counts()
    .sort_values(ascending=False)
)

print(cluster_sizes)

cluster
-1     1851
 13     693
 16     289
 24     242
 31     173
 21     163
 3      146
 20     129
 25     114
 17     105
 14     102
 8      102
 11      98
 23      87
 12      71
 0       57
 15      54
 27      49
 18      43
 7       41
 9       40
 28      38
 5       36
 2       33
 6       32
 19      30
 22      30
 10      29
 29      27
 26      26
 4       24
 1       23
 30      23
Name: count, dtype: int64

In [40]:
largest_cluster = cluster_sizes[cluster_sizes.index != -1].index[0]

print(largest_cluster)

13

In [41]:
largest_cluster = cluster_sizes[cluster_sizes.index != -1].index[0]

print(largest_cluster)

13

In [42]:
samples = dev_df[
    dev_df["cluster"] == largest_cluster
]["clean_text"]

for i, complaint in enumerate(samples.head(10), 1):
    print(f"\nComplaint {i}")
    print(complaint)
    print("-"*80)

Complaint 1
i am writing to formally file a complaint regarding an account listed in your system that utilizes my residential address. on or around xx/xx/xxxx, i received a letter from american express dated xx/xx/xxxx. the letter was addressed to xxxx xxxx and referenced an account ending in xxxx. the correspondence confirmed the cancellation of said account. xxxx xxxx xxxx does not reside at this address ( xxxx xxxx xxxx, xxxx xxxx, nj ). this individual has no legal right to use this property for billing or correspondence. the association of this individual with my residence suggests either a clerical error in your database or potential application fraud where my address was used without my consent. i request that you immediately take the following actions : 1. remove my address ( xxxx xxxx xxxx, xxxx xxxx, nj xxxx ) from the profile associated with xxxx xxxx and account # xxxx immediately. 2. cease all future correspondence addressed to this individual at my home. 3. investigate this account for potential fraudulent activity regarding the falsification of residence. please consider this letter a formal notice to correct your records.
--------------------------------------------------------------------------------

Complaint 2
ive had a bread cash back amex credit card for about four months. aside from their many website glitches and outages, the more important issue is their assumption that there was fraud on my fraudless account ; therefore, my card was locked three times, and unlocked twice. after three phone calls and one snail mail letter, my rectifying efforts resulted in them constantly kicking the can down the road. i was told of ongoing investigations, prompted by them, not me. the last communication from them ( via snail mail letter ) asked me to call them within 30 days, or the account would be closed. i called immediately after receiving the letter. again, the can was kicked, pending further investigation. i told them to close the account, then added that they earned their many negative online reviews ( one site posts 73 % negatives ). i have a second fraudless bread credit card under investigation, which is about to cheat me out of {$50.00} cash back. i was {$17.00} short of earning it, and then it was locked. i expect this account to undergo the same scenario as the aforementioned. i assume that bread is using this tactic to claw back any earned cash rewards.
--------------------------------------------------------------------------------

Complaint 3
i had a credit balance on my amex card for almost {$3900.00}. on xxxx/xxxx/2016, i submitted a request for a refund of the credit balance. the amount was deducted from my account and told me to expect a check. several weeks later, i still had not received a check. on on xxxx/xxxx/16, i called phone # on back of amex card. spoke with xxxx, emp number xxxx. this person said the check had been mailed to my work address ( i never received it at my workplace, and the work address was not the amex address of record ). i was told that amex would issue new check to be sent to the address of record on xxxx xxxx, xxxx hi. today, it is xxxx/xxxx/16, and i have received nothing. what especially angers me is that a prior large credit refund took three years for amex to pay to me. they ultimate did issue a check, but for the original amount without any interest. i had called them during the 3 year period but they had said the check had already been cashed ( which was untrue ). please, please, help me get my money back!
--------------------------------------------------------------------------------

Complaint 4
xxxx xxxx xxxx xxxx xxxx xxxx xxxx xxxx xxxx, mi xxxx xxxx attn : american express xxxx xxxx xxxx xxxx xxxx xxxx, ca xxxx cc/ cfpb dear sir/madam, i am writing to express my deep concern regarding the recent actions taken by american express concerning my credit card account. as a consumer, i believe that my rights under the federal equal credit opportunity act have been violated.after my credit card application was approved and i had already made purchases totaling {$6900.00}, i was surprised to find that my account was frozen and that i was being asked to provide income verification. while i understand the importance of financial responsibility and transparency, i believe that freezing my account after approval and requiring me to disclose sensitive financial information such as my bank account balance goes against the principles outlined in the equal credit opportunity act.i am offended by the implication that my ability to manage credit is contingent upon disclosing personal financial details beyond what is necessary for the application process. requiring me to call my bank and verify my account 's ending balance is not only an invasion of privacy but also a violation of my federally protected consumer rights.i kindly request that american express rectify this situation promptly. failure to do so may compel me to escalate this matter to the consumer financial protection bureau and the securities and exchange commission. i trust that american express will take the necessary steps to resolve this issue and uphold its commitment to fair and equitable treatment of all its customers.thank you for your attention to this matter. i look forward to a swift and satisfactory resolution. lastly i would like to advise that i have sent a notarized copy of this letter to the above address as i am also requesting a response to this notice in writing. thankyou sincerely, xxxx xxxx kind regards,
--------------------------------------------------------------------------------

Complaint 5
i have been an american express member for xxxx years. i have always had my payments on automatic payment for xxxx years. this month, without cause or reason, amex cancelled my account. when i called to discuss this, i was bounced around from xxxx foreign country call center to another. i could not understand what the agents were saying half the time, because they could not speak proper xxxx. my last experience with american express, left me feeling not so " american ''. what i could understand from the conversation was my account was cancelled for " collections ''. how can you cancel an account that is xxxx xxxx xxxx for " collections '', when i have never been late in xxxx years? is this how you treat a xxxx year customer?
--------------------------------------------------------------------------------

Complaint 6
subject : formal complaint against american express in regards to xxxx xxxx xxxx dear consumer financial protection bureau, i am filing a formal complaint against american express ( amex ) and merchant xxxx xxxx regarding a misrepresented rental property and amexs negligent handling of my dispute. this issue has caused significant financial harm and emotional distress over the course of nearly two years and has placed me on the brink of bankruptcy. timeline of events 1. on xx/xx/year>, i was preapproved for a rental property with xxxx xxxx xxxx. i received an invoice with one option to pay now but was not presented with or required to agree to any terms and conditions prior to payment. xxxx. after entering the property on xx/xx/year>, i discovered it was misrepresented compared to the online listing. i promptly reversed the payment after reporting this misrepresentation. xxxx. the merchant later claimed i was shown terms and conditions on xx/xx/year>, at xxxx xxxx full day after the booking and payment had already been completed. this contradicts the timeline and proves the terms were never provided prior to booking. xxxx. amex sided with the merchant, repeatedly citing the disputed terms and conditions, despite clear evidence of timeline discrepancies. amex negligence xxxx. i opened a chargeback on xx/xx/year>, citing property misrepresentation. amex initially credited my account but reversed their decision after accepting the merchants conflicting documentation. xxxx. over the course of seven separate attempts, i provided extensive evidence ( text messages, timelines, and merchant-provided documents ) proving the misrepresentation and discrepancies. amex, however, refused to properly investigate or acknowledge the evidence. financial and emotional impact 1. due to amexs mishandling of this dispute, i was unable to pay the balances on my accounts, resulting in : closure of both amex accounts. derogatory marks on my credit report, severely impacting my credit score. a financial burden that has placed me on the brink of bankruptcy. 2. the emotional toll from nearly two years of stress, repeated disputes, and financial instability has been profound. enclosed supporting evidence timeline of events proving the booking occurred on xx/xx/year>. text message correspondence with the merchant showing no terms and conditions were provided at the time of booking. merchants own documentation, which inconsistently claims terms were provided on xx/xx/year>. amex communications dismissing my evidence and improperly siding with the merchant. i trust the cfpb will investigate this matter thoroughly and help facilitate a fair resolution. please contact me at your earliest convenience if additional information or documentation is needed. thank you for your attention to this matter sincerely, xxxx xxxx
--------------------------------------------------------------------------------

Complaint 7
i received a letter from american express in late xxxx ( i believe ) more or less stating that my interest rate on my credit card was being adjusted to nearly triple the rate i have had for almost 23 years. the reason was not one wherein i did anything to default on my card terms and conditions or anything of the like. i called in xxxx to address the matter and was told that american express needed to align its card product to be in better alignment with market standards. it was due to a subjective business decision in other words. i was told that in order to contest the interest rate change, i was required to go though an appeal process. required. the supervisor with whom i spoke said she would submit one for me stating she understood and was in agreement that i had a stellar relationship with them for a long time and never paid late as i stated etc ... within three days i received a letter in the mail stating that my fico score which was very good. but amex still has chosen to raise my interest rate without material reason. the letter provided a number to further discuss and what proceeded was a sham. i spent nearly an hour on the phone being passed around to various persons because the number provided was misleading in that i could get further information. i have a record of all of the dates that i called and with whom i spoke. i suspected they were running a game hoping i would go away. amex is imposing usury level interest charges to suit their greed. if you provide a line of credit based on credit worthiness and the consumer has not breached any of the terms, it is beyond unreasonable to just decide to triple the interest rate because my guess is amex did not like the fact that i had recently let me balance run higher than normal. i have that right because it is in line with what i was approved for and i even paid off the entire balance. one time i was even connected to a group called responsible lending and spoke with a very reasonable rep who demonstrated the patience to hear out all details and he even said he did not understand why my interest rate would be raised so high. yet he could not help me ultimately because i had been improperly transferred for the 3rd time that day. that aside, in terms of quality of customer service, in all of my nearly 23 years with this company, amex gets an f+ for making a decision to communicate such an egregious unfounded change to my interest rate after being an excellent customer so long. there is a deficiency in the internal processes to handle these sorts of matters which leads me to believe it is intentional. i am not going to just swallow a usury application of a charge. i made many efforts to identify the proper party to speak with re : what would become a sfp complaint and some were just ignorant and others just did not seem to care. very unfortunate.
--------------------------------------------------------------------------------

Complaint 8
i have called multiple times in xxxx and xx/xx/2023 to ask if the points that disappeared after i got it partially redeemed will show up the next billing cycle so i can redeem them again. the agents i had spoken to said yes i will be able to redeem the rest of the points which is exactly xxxx points after the partial redemption which was xxxx, during the next billing cycle. it has been over 3 months and i still havent gotten my points/ money. i want the points back.
--------------------------------------------------------------------------------

Complaint 9
i reported suspicious activity on my credit card in xxxx to chase bank also informing them that my card was missing. the suspicious activity was reported prior to the transaction clearing. chase will not credit my account for the fraudulent charges to my account of {$8700.00} my chase bill shows the following xxxx/xxxx/2016 debit card transaction imagexxxx xxxx xxxx xxxx xxxx x xxxx ( exchg rte ) + xxxx ( exchg rte {$8700.00} first of all xxxx x xxxx = xxxx not xxxx chase is now trying to use my confusion about the matter ( which mathematically makes no sense ) to say that i 'm somehow at fault, or changing my story because i originally though it to be an overcharge. chase will not contact the merchant for proof of this transaction, even though there have been multiple fraudulent transactions reported from this merchant. i do not feel it is safe to use a debit card if this type of fraudulent activity is not protected.
--------------------------------------------------------------------------------

Complaint 10
i recieved a bankamericard cash rewards card xxxx. the rules then were 3x cashback on gas, grocery, and drugstore purchases for the first 6 months. plus, you earn 1 % cashback on all other purchases. after that was only 1 % for every purchase. this took over 5 years to reach the {$300.00} mark for cash rewards and would have been 25 % more, if it was transferred into the checking account i have had since the 90 's. but they decided to change all the rules and xxxx people out of {$45.00} of the money originally promised for over 5 years. they decided to change it to 10 % now in xxxx 2015. i just finally got to {$300.00} last month 's statement, i was told. i am angry that, it took over 5 years to try and use my card as much as i could to try and get to the {$300.00}, so i could benefit from the 25 %, the reason, i wanted to have the card in the first place. now only to find out when i tried to transfer my {$300.00} it took over 5 years to reach, that i was not going to get {$45.00} of that money now. to me, this is a way to xxxx everyone who originally got this card, we all lose out on the 25 %. which bankamericard is now making money from screwing us all by changing the rules to take it to 10 %, they are making {$45.00} a head from everyone this has happened to, that has taken years to reach this goal. now we are told, sorry plans changed. well, i do n't know about anyone else, but this is not very good business. i feel like i just wasted over 5 years of my life, thinking i was soon going to get {$75.00} extra for using this card. how convenient, the average use of this card, will take the average person that long to get to {$300.00}, so they make more money off of screwing us, by changing the rules, when they see how many people are going to reach their {$300.00} goals. this makes me sick. i want my money from my original, reason for signing up for this card in the first place. if i would of known they were going to pull some xxxx like this, i would of never signed up for the card in the first place. seems a little crooked business strategy if you ask me, not honoring that long of a customer 's contract. i called xxxx before writing this, xxxx, customer service, would n't or was n't able to do anything for me. i told her, sounds like i need to take my money out of the bank and cancel this card, cuz what is the next horrible thing you are going to change? i am not willing to wait to find out.
--------------------------------------------------------------------------------

In [43]:
cluster_summary = (
    dev_df.groupby("cluster")
    .agg(
        complaints=("clean_text", "count"),
        unique_issues=("Issue", "nunique")
    )
    .sort_values("complaints", ascending=False)
)

print(cluster_summary.head(10))

         complaints  unique_issues
cluster
-1             1851             42
 13             693             35
 16             289             26
 24             242             29
 31             173             18
 21             163             18
 3              146             11
 20             129             16
 25             114              7
 17             105             24

In [44]:
cluster = 13

samples = dev_df[
    dev_df["cluster"] == cluster
][["Issue", "clean_text"]].sample(10, random_state=42)

for _, row in samples.iterrows():
    print("Issue:", row["Issue"])
    print(row["clean_text"])
    print("-" * 100)

Issue: Balance transfer
in 2016 american express ended its role as the exclusive card for xxxx, with that role being taken over by xxxx. my existing amex/xxxx card had a balance at the time of the change and that balance was transfered to the xxxx account. subsequently, amex mailed me an offer to open a new account with them ; the offer extended stated that balance transfers and purchases would be interest free for 15 months. taking advantage of this i transferred the xxxx balance ( the original amex/costco balance ) back to amex under the new, interest free offer. however, in the first billing cycle, amex charged me interest on the balance transfer made, contrary to their offer terms under which i made said transfer. i called amex and opened a complaint. after a month of not hearing anything i called amex and inquired of the status. i was told a decision was forthcoming. i waited another 4 weeks and phoned again. during this xxxx call amex made the assertion that the interest free offer only applied to purchases, not balance transfers, despite the fact that the offer letter clearly states both purchases and balance transfers would be interest free for 15 months. the customer rep supervisor asked for the offer number printed on the offer letter. i provided this to her and she responded that the offer number did not cover balance transfers. i replied that her position was that the document they sent me, which i still possess, which states both balance transfers and purchases would be interest free for 15 months, did n't say what what was printed on the paper. amex requested a copy of the offer, which i scanned and emailed to them. 3 days later i received a voice message from amex, saying to call them at the provided number and enter a xxxx digit code. i called the number, but the automated system requires a xxxx digit code. at this point i believe amex is purposely avoiding honoring their offer terms and purposely making it difficult to reach them in an effort to make me drop the issue.
----------------------------------------------------------------------------------------------------
Issue: Closing your account
subject : request for review of chase credit card account closures and inconsistent handling to whom it may concern, i am writing to formally request your assistance in reviewing a matter involving jpmorgan chase bank and the closure of my credit card accounts. while i take responsibility for an error on my part, i believe chases handling of my accountsparticularly the issuance and subsequent closure of a third accountraises concerns about their processes and fairness. background i held xxxx credit card accounts with chase : account ending in xxxx : opened on xx/xx/xxxx, and closed on xx/xx/xxxx. account ending in xxxx : opened on xx/xx/xxxx, and closed on xx/xx/xxxx, alongside the first account. third account : opened and closed in xx/xx/xxxx, issued through chases system as a pre-approved offer after the closure of my first xxxx accounts. the first xxxx accounts were in good standing, with no missed or late payments. occasionally, i filed disputes through chases app when dissatisfied with purchases, and these disputes were often resolved in my favor. the incident the issue began when i disputed a {$38.00} charge from an auto mechanic. the mechanic charged me for an incomplete service, and i believed the charge was unjustified. while attempting to dispute the charge via the chase app, i mistakenly selected the option for an " unauthorized transaction '' instead of accurately describing the issue. following an investigation, chase determined that this misuse, along with past disputes, violated their policies, leading to the closure of my first xxxx accounts. while i regret the error and accept responsibility, i am concerned about what happened next. concerns about chases handling issuance and closure of the third account : after closing my first xxxx accounts, chases system pre-approved me for a third credit card, which was automatically approved when i accepted the offer via their mobile app. i applied in good faith, believing this indicated a willingness to continue our relationship. however, chase closed this account shortly after its issuance, citing the same reasons as the previous closures. this inconsistency is both confusing and frustrating. lack of transparency : while i understand chases right to close accounts for policy violations, issuing and then closing the third account undermines the rationale for the initial closures. additionally, chase removed the details of this third account from my online banking profile, making it difficult for me to reference it. impact on my credit report and score : the closure of all three accounts has been reported as closed by grantor on my credit report. despite my excellent payment history and a prior credit score of around xxxx, these closures reduced my score to xxxx. this has negatively affected my ability to obtain new credit, as recent applications to other issuers were denied. requested resolution i respectfully request the following : a formal review of chases decision to issue and then close the third account after terminating my first xxxx accounts. an explanation of chases internal processes to ensure customers are not subjected to such inconsistent treatment. if possible, reconsideration of the decision to close my third account, as its issuance implied a willingness to maintain the relationship. i acknowledge the importance of adhering to policies and take responsibility for my mistake in filing the dispute. however, i believe chases actions, particularly the issuance and closure of the third account, were inconsistent and have unnecessarily impacted my credit score and financial standing. thank you for your time and attention to this matter. i look forward to your response and hope for a fair resolution. sincerely, xxxx xxxx xxxx xxxx xxxx, xxxx xxxx, ny xxxx xxxx xxxx
----------------------------------------------------------------------------------------------------
Issue: Closing/Cancelling account
the issue is as follows, out of the clear blue jpmorgan chase bank decided to shut down both of my credit cards. i used the cards regularly for my daily purchases. please note my credit is xxxx with all xxxx credit reporting agency 's. i used 2 % of my entire credit lines and i pay off my bills bi-weekly in full. in order words i have no risk whatsoever to this or any other financial institution. i truly believe that i was discriminated against in this situation and i want this matter investigated accordingly.
----------------------------------------------------------------------------------------------------
Issue: Incorrect information on your report
i had a small business that failed. i had a company credit card that all employees used. it was my fault that employees took advantage of my business in this way by making liberal and unauthorized purchases on the credit card. but, this was a business credit card, not a personal credit card and chase bank is treating it as a personal debt when it was not a personal debt. i feel that if this will affect me personally, then the employees that used the credit cards should be affected personally also. after i sold the assets, the business paid or settled the remaining open debt balances. this business chase credit card is being attached to my personal credit report even though i never signed a personal guaranty for the credit card. chase bank harassed and called me daily to pay the balance on the credit card back in 2020. since it was affecting my personal ability to move on in life and have access to credit again, i offered chase a settlement. i paid the amount we settled on personally and they were supposed to remove the record from my personal credit report. they have not done it and recently i was denied credit and this was a major reason for the rejection. this poor history on my personal credit report that should never have been reported there but to xxxx xxxx xxxx, is causing me harm in my personal life.
----------------------------------------------------------------------------------------------------
Issue: Problem with a purchase shown on your statement
on xx/xx/2024 i was visiting xxxx on a cruise. i went to xxxx to xxxx and went to a local merchant to purchase a souvenir magnet. the merchant insisted on selling me coins as well and would keep trying to bargain on a price with me. after xxxx mins of no-s he eventually said xxxx ( {$21.00} ) for both the magnet and the coins. i agreed and he took my credit card and charged me. i did not see the reader, a screen, or anything and when i asked for a receipt he refused. i did not sign anything either. a few hours later i see a charge on my card from the merchant for {$260.00} dollars. by then my ship already departed and i could not contact the merchant. i immediately notified my bank, chase, and they said they would handle it. now almost 2 months later chase is saying that the charges are valid and they will not be assisting me with this dispute because the merchant provided a receipt of the amount. of course he provided a receipt, he was the one that charged me that insane amount for a magnet and coins! i tried calling chase and telling them the situation but the insisted that i was " not accepting the facts ''. how can i provide any more information that a merchant overcharged me? chase bank has ineffectively handled this situation and should be penalized for treating their customers with such disregard.
----------------------------------------------------------------------------------------------------
Issue: Problem with a purchase shown on your statement
i was a victim of identity theft in xxxx of xxxx. my phone number, email, social security number, checking and savings accounts along with various credit cards in my name were all hacked. i was able to resolve all of the above issues except for my xxxx xxxx chase xxxx cards which i had not previously used. someone was able to obtain the card information and download it onto their phone ( i still have the card in my posession ) they then charged in xxxx day almost {$10000.00} to the card from xxxx. i have reported this several times to chase and they have said they have investigated but not removed the charges 3 times. the last time i called on xx/xx/xxxx, they reopened investigation again and asked me to send a copy of my credit report showing that i have a security freeze on my account which i did. they said they would respond in 4 days but when i called again this morning, they gave a run around answer and said it will be xxxx more days. i am currently battling xxxx xxxx xxxx and the added stress of this situation is detrimental to my health. please advise if you can help. thank you, xxxx xxxx
----------------------------------------------------------------------------------------------------
Issue: Problem with a purchase shown on your statement
my name is xxxx xxxx xxxx. this letter i tried to send to chase card services. the card that was used had the last four digits xxxx. i did not use that card on xxxx and xxxx for those 5 charges you added back to my card in xxxx. i sent the letter below to my job because i was in the xxxx on xxxx to get xxxx. i was home on xxxx following my xxxx xxxx to prepare for the xxxx. i was put on a xxxx xxxx at xxxx xxxx on xxxx. this letter below i sent to my job to be excused from work. i have an email from you asking did i recognize a charge someone tried to make at xxxx xxxx over xxxx which thankfully chase declined on xxxx. i responded no i did not make that charge. you changed my card. i did not get it. i believe someone tried to use that card and you canceled that card and sent me another card. yet, you say i made charges i did not make! i want you to take all these charges off my card! those charges were on xxxx and xxxx that you added back to my bill. i i have been a customer too long to be treated like this! below is the letter i sent to my job that proves i was in the hospital on xxxx. i was told to send this letter to the email provided by your staff. it was sent back to me as undeliverable. sincerely, xxxx xxxx
----------------------------------------------------------------------------------------------------
Issue: Closing your account
getting notifications about a credit card i never applied for
----------------------------------------------------------------------------------------------------
Issue: Fees or interest
complaint regarding jpmorgan chases handling of annual fee refunds i was charged the annual fee on my chase sapphire reserve card on xx/xx/xxxx. within xxxx xxxx, i called chase several times to confirm my options. each time, representatives assured me i could cancel or downgrade the card and still receive a full refund. on more than xxxx call, they gave me the exact date by which i needed to act, and xxxx associate even confirmed this was a standard policy. relying on these assurances, i downgraded before that date. instead of refunding the fee, chase charged me a prorated amount. at first i assumed this was an adjustment, but later saw i was effectively double-charged xxxx full annual fee plus a prorated portion despite repeated promises of a full refund. when i escalated, the first associate again confirmed i should have been refunded. but a xxxx then denied it, offering arbitrary reasons. the xxxx even argued that my use of unrelated card benefits justified withholding the refund a claim that is illogical, deceptive, and not disclosed anywhere in chases policies. this amounts to chase retroactively changing terms and contradicting what its own representatives told me. chases own staff, as well as multiple consumer resources and reports, confirm that full refunds are available within the deadline ( actual date ) communicated to me whether via cancellation or product change. this conduct violates consumer protection principles and constitutes misrepresentation. i request : a full refund of the annual fee, as promised. written clarification of chases official policy on refunds for cancellations vs. downgrades. review of call logs and scripts to prevent further misrepresentation.
----------------------------------------------------------------------------------------------------
Issue: Other features, terms, or problems
over the weekend, i received a text stating the following : amex acct status - free msg : xxxx, did you get our email? explore payment plans in your inbox or at xxxx text stop to unsubscribe. i texted stop and this is what i received : m amex free credit msg : you will no longer receive account alerts text messages. you may still receive free fraud alerts. please call xxxx for help i tried texting the new owner of phone number no xxxx here -- no response. i have had this phone number for over 2 years and can not understand how american express can send out with the account holders name, and indication that their account payment status is late! isn't this an invasion of privacy, especially for a phone number that has not been verified in over 2 years! furthermore, calling that number, american express confirmed that the account was delinquent, yet stated that the number may be outdated. my concern, had that been my account, why are they giving the name and account status via text without confirmation on a phone number ( confirmation within 6 mos. ). furthermore, there is no option to state, other than calling, wasting my time, money, etc. to opt completely out, as there is the threat of still receiving fraud alerts. i asked for id 's of agents and was refused, i was hung up by agents saying i am not an account holder, i asked for confirmation ( in writing ) that i would not be bothered by this company with fraud alerts and was refused. the company thinks it's god and has a god-like complex they should be fined and policies changed to get to upper management!
----------------------------------------------------------------------------------------------------

In [45]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

representatives = {}

for cluster in sorted(dev_df["cluster"].unique()):
    if cluster == -1:
        continue

    indices = dev_df[dev_df["cluster"] == cluster].index

    cluster_embeddings = embeddings[indices]

    centroid = cluster_embeddings.mean(axis=0)

    similarities = cosine_similarity(
        cluster_embeddings,
        centroid.reshape(1, -1)
    ).flatten()

    representative_index = indices[similarities.argmax()]

    representatives[cluster] = representative_index

In [46]:
cluster = 13

idx = representatives[cluster]

print(dev_df.loc[idx, "clean_text"])

hello- i have been a chase united cardholder since xxxx. in xx/xx/xxxx, i was unexpectedly informed that my credit card account had been permanently closed. i only discovered this after my card was declined during a transaction, and i called customer service. at that time, representatives provided limited information and stated that a letter would follow with more details. however, the letter contained no additional explanationonly confirmation of the account closure. at the time of closure, my account had a {$0.00} balance, with all payments fully current. i had several upcoming travel plans booked on the card, including flights and a xxxx trip, which were canceled because chase flagged them as fraudulent and reversed the charges. this caused my xxxx tickets to be rescinded, requiring me to repurchase them out of pocket. i have not yet been reimbursed for this cost, despite multiple follow-ups. since the week of xx/xx/xxxx, ive contacted chase several times, but each representative has been unhelpful, repeatedly stating i would receive a response within xxxx hours, which has not occurred. on xx/xx/xxxx, a supervisor informed me that i could not speak directly to the back-end team and said they would follow up via email, advising it could take up to two weeks. as of today, xx/xx/xxxx, i have received no updates. to make matters worse, i was informed that chase has requested refunds from vendors i had valid transactions with months ago, such as xxxx stays. this undermines my reputation with those businesses. i am deeply concerned about how this situation has been handled. my account, which has been open for over a year and has consistently been in good standing, is now being labeled as fraudulent without clear justification. i have not engaged in any illegal activity and deserve transparency and the return of my funds, particularly for my xxxx trip. please escalate this matter. i would appreciate a detailed explanation and timely resolution. sincerely, xxxx xxxx xxxx xxxx xxxx

In [47]:
cluster_report = (
    dev_df[dev_df["cluster"] != -1]
    .groupby("cluster")
    .agg(
        complaints=("clean_text", "count"),
        top_company=("Company", lambda x: x.mode().iloc[0] if not x.mode().empty else None),
        top_issue=("Issue", lambda x: x.mode().iloc[0] if not x.mode().empty else None),
    )
)

cluster_report.head()

,complaints,top_company,top_issue
cluster,,,
0,57,"EQUIFAX, INC.",Problem with a company's investigation into an existing problem
1,23,"EQUIFAX, INC.",Problem with a company's investigation into an existing problem
2,33,"EQUIFAX, INC.",Incorrect information on your report
3,146,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",Problem with a company's investigation into an existing problem
4,24,"EQUIFAX, INC.",Incorrect information on your report